# -*- coding: utf-8 -*-
"""Simple Billing App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SWGngyS2BP5CCPbex2NgdAHuAfJDtJdJ
"""

print("🧾 Welcome to the Simple Billing App 🧾\n")

# To store all items
items = []

while True:
    name = input("Enter item name: ")
    quantity = int(input("Enter quantity: "))
    price = float(input("Enter price per item: "))

    total = quantity * price
    items.append({
        "name": name,
        "quantity": quantity,
        "price": price,
        "total": total
    })

    print(f"Added: {name} x {quantity} @ ₹{price:.2f} each = ₹{total:.2f}\n")

    more = input("Do you want to add another item? (yes/no): ").strip().lower()
    if more != "yes":
        break

# Print final bill
print("\n🧾 Final Bill 🧾")
print("-" * 40)
print(f"{'Item':15} {'Qty':>5} {'Price':>10} {'Total':>10}")
print("-" * 40)

grand_total = 0
for item in items:
    print(f"{item['name']:15} {item['quantity']:>5} ₹{item['price']:>8.2f} ₹{item['total']:>9.2f}")
    grand_total += item["total"]

print("-" * 40)
print(f"{'Grand Total':>32} ₹{grand_total:.2f}")
print("Thank you for shopping! 🛍️")